/**
 * #mdx/editor/plugins/task-list.plugin.js
 * @file Task List Plugin
 * Adds interactivity to GFM-style task list items (`- [ ] task`).
 * The initial HTML is already generated by a custom listitem renderer in the core.
 * This plugin hooks into `domUpdated` to attach event listeners for toggling tasks.
 */

export class TaskListPlugin {
    name = 'core:task-list';

    /**
     * @param {import('../core/plugin.js').PluginContext} context
     */
    install(context) {
        context.on('domUpdated', ({ element, options, renderer }) => {
            // Similar to ClozePlugin, use a WeakMap to avoid re-attaching listeners.
            if (!TaskListPlugin.listenerMap) TaskListPlugin.listenerMap = new WeakMap();
            if (TaskListPlugin.listenerMap.has(element)) return;

            const listener = (event) => {
                const checkbox = event.target.closest('.task-list-item input[type="checkbox"]');
                if (checkbox) {
                    const detail = {
                        taskText: checkbox.closest('li').textContent.trim(),
                        isChecked: checkbox.checked,
                        element: checkbox
                    };

                    // Emit a global event
                    context.emit('taskToggled', detail);

                    // Also fire the per-render callback
                    options.on?.taskToggled?.(detail);
                }
            };
            
            element.addEventListener('click', listener);
            TaskListPlugin.listenerMap.set(element, listener);
        });
    }
}
