import { FS_MODULE_CHAT, FS_MODULE_AGENTS } from '@itookit/common';
import type { WorkspaceConfig } from '@itookit/app-shell';

export type { WorkspaceConfig };

export const WORKSPACES: WorkspaceConfig[] = [
    {
        elementId: 'settings-workspace',
        moduleName: 'settings_root',
        slug: 'settings',
        syncEnabled: false,
        type: 'settings',
        title: 'Settings',
        supportedFileTypes: [],
        readOnly: true,
        aiEnabled: false,
        mentionAble: false,
        initialSidebarCollapsed: false,
    },
    {
        elementId: 'agent-workspace',
        moduleName: FS_MODULE_AGENTS,
        slug: 'agents',
        syncEnabled: true,
        isSystem: true,
        type: 'agent',
        title: 'Agents',
        supportedFileTypes: ['agent'],
        plugins: ['core:titlebar'],
        mentionScope: ['agents', 'prompts', 'projects'],
        mentionAble: false,
        aiEnabled: false,
    },
    {
        elementId: 'anki-workspace',
        moduleName: 'anki',
        slug: 'anki',
        syncEnabled: true,
        type: 'standard',
        title: 'Anki Memory Cards',
        supportedFileTypes: ['anki', 'markdown'],
        plugins: [
            'cloze:cloze',
            'cloze:cloze-controls',
            'cloze:memory',
            'autocomplete:mention',
            'autocomplete:tag',
        ],
        mentionScope: ['*'],
        mentionAble: true,
        aiEnabled: true,
    },
    {
        elementId: 'prompt-workspace',
        moduleName: 'prompts',
        slug: 'prompts',
        syncEnabled: true,
        type: 'standard',
        title: 'Prompt Library',
        supportedFileTypes: ['prompt'],
        mentionAble: true,
        aiEnabled: true,
    },
    {
        elementId: 'project-workspace',
        moduleName: 'projects',
        slug: 'projects',
        syncEnabled: true,
        type: 'standard',
        title: 'Projects',
        supportedFileTypes: ['project'],
        mentionAble: true,
        aiEnabled: true,
    },
    {
        elementId: 'email-workspace',
        moduleName: 'emails',
        slug: 'emails',
        syncEnabled: true,
        type: 'standard',
        title: 'Email Drafts',
        supportedFileTypes: ['email'],
        mentionAble: true,
        aiEnabled: true,
    },
    {
        elementId: 'private-workspace',
        moduleName: 'private',
        slug: 'private',
        syncEnabled: false,
        isProtected: true,
        type: 'standard',
        title: 'Private Notes',
        supportedFileTypes: ['private'],
        mentionScope: [],
        mentionAble: true,
        aiEnabled: true,
    },
    {
        elementId: 'llm-workspace',
        moduleName: FS_MODULE_CHAT,
        slug: 'chat',
        syncEnabled: true,
        type: 'chat',
        title: 'AI Sessions',
        supportedFileTypes: ['chat'],
        mentionScope: ['*'],
        mentionAble: true,
        plugins: [],
        aiEnabled: false,
    },
];
