// @file vfs/core/errors/ErrorCodes.ts

export enum ErrorCode {
  // 通用错误
  UNKNOWN = 'UNKNOWN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  
  // 节点错误
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  INVALID_PATH = 'INVALID_PATH',
  INVALID_OPERATION = 'INVALID_OPERATION',
  
  // 权限错误
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  READ_ONLY = 'READ_ONLY',
  
  // 事务错误
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TRANSACTION_ABORTED = 'TRANSACTION_ABORTED',
  
  // 插件错误
  PLUGIN_NOT_FOUND = 'PLUGIN_NOT_FOUND',
  PLUGIN_LOAD_ERROR = 'PLUGIN_LOAD_ERROR',
  DEPENDENCY_ERROR = 'DEPENDENCY_ERROR',
  
  // 存储错误
  STORAGE_ERROR = 'STORAGE_ERROR',
  CONNECTION_ERROR = 'CONNECTION_ERROR',
  
  // 同步错误
  SYNC_ERROR = 'SYNC_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR'
}
