/**
 * @file mdxeditor/mdxplugins/task-list.plugin.js
 * @description Adds interactivity to GFM-style task list items (`- [ ] task`).
 * The initial HTML is already generated by a custom listitem renderer in the core.
 * This plugin hooks into `domUpdated` to attach event listeners for toggling tasks.
 */

/** @typedef {import('../core/plugin.js').PluginContext} PluginContext */

export class TaskListPlugin {
    name = 'core:task-list';

    /**
     * A map to track which elements we've already attached listeners to, preventing duplicates.
     * @type {WeakMap<HTMLElement, EventListener>}
     */
    static listenerMap = new WeakMap();

    /**
     * @param {PluginContext} context
     */
    install(context) {
        context.on('domUpdated', ({ element, options, renderer }) => {
            // Return early if we've already attached a listener to this element
            if (TaskListPlugin.listenerMap.has(element)) return;

            const listener = (event) => {
                const target = /** @type {HTMLInputElement} */ (event.target);
                const checkbox = target.closest('.task-list-item input[type="checkbox"]');
                if (checkbox) {
                    const detail = {
                        taskText: checkbox.closest('li').textContent.trim(),
                        isChecked: target.checked,
                        element: checkbox
                    };

                    // Emit a global event
                    context.emit('taskToggled', detail);

                    // Also fire the per-render callback
                    options.on?.taskToggled?.(detail);
                }
            };
            
            element.addEventListener('click', listener);
            TaskListPlugin.listenerMap.set(element, listener);
        });
    }
}
